apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - web-api.yaml
  - web-front.yaml
  - gateway.yaml
  - prometheus-stack.yaml
  - loki-logs.yaml
  - fluentbit-logs.yaml
  - kafka-operator.yaml
  - kafka.yaml
