/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by @hey-api/openapi-ts

import type {
  UploadFileFilesUploadPostResponse,
  ListFilesFilesGetResponse,
  RetryFileFilesFileIdRetryPatchResponse,
  CancelFileFilesFileIdCancelPatchResponse,
} from './types.gen';

const fileResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const uploadFileFilesUploadPostResponseTransformer = async (
  data: any
): Promise<UploadFileFilesUploadPostResponse> => {
  data = fileResponseSchemaResponseTransformer(data);
  return data;
};

const listFilesResponseSchemaResponseTransformer = (data: any) => {
  data.credit_timestamp = new Date(data.credit_timestamp);
  data.results = data.results.map((item: any) => {
    return fileResponseSchemaResponseTransformer(item);
  });
  return data;
};

export const listFilesFilesGetResponseTransformer = async (
  data: any
): Promise<ListFilesFilesGetResponse> => {
  data = listFilesResponseSchemaResponseTransformer(data);
  return data;
};

export const retryFileFilesFileIdRetryPatchResponseTransformer = async (
  data: any
): Promise<RetryFileFilesFileIdRetryPatchResponse> => {
  data = fileResponseSchemaResponseTransformer(data);
  return data;
};

export const cancelFileFilesFileIdCancelPatchResponseTransformer = async (
  data: any
): Promise<CancelFileFilesFileIdCancelPatchResponse> => {
  data = fileResponseSchemaResponseTransformer(data);
  return data;
};
