apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-front
  name: web-front
  namespace: web-front
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: web-front
