apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: files
  labels:
    strimzi.io/cluster: cmp9785-cluster
spec:
  partitions: 12
  replicas: 3
  config:
    retention.ms: 7200000 # 2h
    retention.bytes: 2147483648 # 2GB
    segment.bytes: 1073741824
    cleanup.policy: delete
    compression.type: lz4
    max.message.bytes: 102400
