apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: cmp9785
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: 0.10.0
      helm:
        releaseName: vault-secrets-operator
        valueFiles:
          - $values/infra/argocd/manifests/vault/operator-values.yaml
    - repoURL: https://github.com/vuchuc789/cmp9785-cloud-development
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
