apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-api
  namespace: argocd
spec:
  project: cmp9785
  source:
    repoURL: https://github.com/vuchuc789/cmp9785-cloud-development
    targetRevision: main
    path: infra/argocd/manifests/web-api
    helm:
      valueFiles:
        - values.custom.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
