kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: default-gateway
  namespace: kube-system
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  rules:
    - backendRefs:
        - name: default-http-backend
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-front-gateway
  namespace: web-front
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "cmp9785.vuchuc789.co.uk"
    - "app.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: web-front-generic-app
          port: 3000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-api-gateway
  namespace: web-api
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "api.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: web-api-generic-app
          port: 8000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-gateway
  namespace: argocd
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "deploy.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: argo-cd-argocd-server
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-gateway
  namespace: monitoring
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "monitor.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: prometheus-grafana
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pgadmin-gateway
  namespace: database
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "database.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: pgadmin-pgadmin4
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: kafka-ui-gateway
  namespace: kafka
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "kafka.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: kafka-ui
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: redisinsight-gateway
  namespace: redis
  labels:
    gateway: shared-gateway
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "redis.cmp9785.vuchuc789.co.uk"
  rules:
    - backendRefs:
        - name: redisinsight-service
          port: 80
