replicaCount: 2
image:
  repository: vuchuc781999/cmp9785-api
  tag: m-423a32e
imagePullSecrets: []
service:
  type: ClusterIP
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 500Mi
livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 40
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 5
envFrom:
  - secretRef:
      name: web-api-secret-envs
env:
  - name: LOG_LEVEL
    value: debug
  - name: DB_HOST
    value: postgres-postgresql.database.svc.cluster.local
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: cmp9785
  - name: DB_USERNAME
    value: cmp9785
  - name: CORS_ORIGINS
    value: '["https://cmp9785.vuchuc789.co.uk","https://app.cmp9785.vuchuc789.co.uk"]'
  - name: SOURCE_EMAIL
    value: "noreply@vuchuc789.co.uk"
  - name: FRONTEND_URL
    value: "https://cmp9785.vuchuc789.co.uk"
  - name: OPENVERSE_URL
    value: https://api.openverse.org
  - name: OPENVERSE_CLIENT_ID
    value: "3CH0Q11hWkc30y5GYz3Pre20NohyIv20K0tpf0Ok"
  - name: OPENVERSE_CLIENT_SECRET
    value: "rGHihC7flAYMDgQ3ntBy1pNoAnSQXavBHy7GRFoSdrCbcfDa7O0lSdNHbmn7l8oDVL3cxz4kRN6SRFetvhCx6RLqUC56AuxrHETzpWe222ammxJAjX7gQ9O7XmRJlZwH"
  - name: CDN_URL
    value: https://cdn.cmp9785.vuchuc789.co.uk
  - name: BUCKET_NAME
    value: 13c21c572008135e-cmp9785-cdn-bucket
  - name: KAFKA_SERVERS
    value: '["cmp9758-cluster-cmp9758-dual-role-0.cmp9758-cluster-kafka-brokers.kafka.svc.cluster.local:9092","cmp9758-cluster-cmp9758-dual-role-1.cmp9758-cluster-kafka-brokers.kafka.svc.cluster.local:9092","cmp9758-cluster-cmp9758-dual-role-2.cmp9758-cluster-kafka-brokers.kafka.svc.cluster.local:9092"]'
