replicaCount: 2
image:
  repository: vuchuc781999/cmp9785-api
  tag: m-4bb7091
imagePullSecrets: []
service:
  type: ClusterIP
  port: 8000
resources:
  requests:
    cpu: 200m
    memory: 400Mi
  limits:
    cpu: 1
    memory: 2Gi
livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 40
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 5
volumes:
  - name: sa-key
    secret:
      secretName: web-api-service-account-key
      optional: false
volumeMounts:
  - name: sa-key
    mountPath: "/secret"
    readOnly: true
envFrom:
  - secretRef:
      name: web-api-secret-envs
env:
  - name: DB_HOST
    value: postgres-postgresql.database.svc.cluster.local
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: cmp9785
  - name: DB_USERNAME
    value: cmp9785
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /secret/service-account-key.json
  - name: CORS_ORIGINS
    value: '["https://cmp9785.vuchuc789.co.uk","https://app.cmp9785.vuchuc789.co.uk"]'
  - name: SOURCE_EMAIL
    value: "noreply@vuchuc789.co.uk"
  - name: FRONTEND_URL
    value: "https://cmp9785.vuchuc789.co.uk"
  - name: CDN_URL
    value: https://cdn.cmp9785.vuchuc789.co.uk
  - name: BUCKET_NAME
    value: 13c21c572008135e-cmp9785-cdn-bucket
  - name: KAFKA_SERVERS
    value: '["cmp9785-cluster-cmp9785-dual-role-0.cmp9785-cluster-kafka-brokers.kafka.svc.cluster.local:9092","cmp9785-cluster-cmp9785-dual-role-1.cmp9785-cluster-kafka-brokers.kafka.svc.cluster.local:9092","cmp9785-cluster-cmp9785-dual-role-2.cmp9785-cluster-kafka-brokers.kafka.svc.cluster.local:9092"]'
  - name: REDIS_HOST
    value: 'redis-master.redis.svc.cluster.local'
