replicaCount: 2
image:
  repository: vuchuc781999/cmp9785-app
  tag: m-a1da14e
imagePullSecrets: []
service:
  type: ClusterIP
  port: 3000
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 500Mi
livenessProbe:
  httpGet:
    path: /
    port: 3000
readinessProbe:
  httpGet:
    path: /
    port: 3000
