replicaCount: 1
image:
  repository: vuchuc781999/cmp9785-api
  tag: m-c1bb7cc
imagePullSecrets: []
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi
livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 40
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 5
envFrom:
  - secretRef:
      name: web-api-secret-envs
env:
  - name: DB_HOST
    value: postgres-postgresql.database.svc.cluster.local
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: cmp9785
  - name: DB_USERNAME
    value: cmp9785
  - name: SOURCE_EMAIL
    value: "noreply@vuchuc789.co.uk"
  - name: FRONTEND_URL
    value: "http://localhost:3000"
  - name: OPENVERSE_URL
    value: https://api.openverse.org
  - name: OPENVERSE_CLIENT_ID
    value: "sample"
  - name: OPENVERSE_CLIENT_SECRET
    value: "sample"
