"""Delete heroes table

Revision ID: 1228f62b292b
Revises: eab069000c1a
Create Date: 2025-03-07 23:06:27.715215

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1228f62b292b'
down_revision: str | None = 'eab069000c1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_heroes_age', table_name='heroes')
    op.drop_index('ix_heroes_name', table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'heroes',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='heroes_pkey'),
    )
    op.create_index('ix_heroes_name', 'heroes', ['name'], unique=False)
    op.create_index('ix_heroes_age', 'heroes', ['age'], unique=False)
    # ### end Alembic commands ###
