"""Add timestamps to file tables

Revision ID: 54b63c19812d
Revises: 5fcd0d373aa0
Create Date: 2025-04-13 22:29:53.602609

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54b63c19812d'
down_revision: str | None = '5fcd0d373aa0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'file_descriptions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'created_at')
    op.drop_column('file_descriptions', 'created_at')
    # ### end Alembic commands ###
