"""Add cancelled status

Revision ID: 6592ad9f4e2c
Revises: 9aab4d1bfaaf
Create Date: 2025-04-16 21:24:04.449721

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6592ad9f4e2c'
down_revision: str | None = '9aab4d1bfaaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='fileprocessingstatus',
        new_values=['pending', 'processing', 'success', 'failed', 'cancelled', 'unknown'],
        affected_columns=[
            TableReference(table_schema='public', table_name='files', column_name='status')
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='fileprocessingstatus',
        new_values=['pending', 'processing', 'success', 'failed', 'unknown'],
        affected_columns=[
            TableReference(table_schema='public', table_name='files', column_name='status')
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
