"""Add queuing status

Revision ID: 7ba304c8cf80
Revises: 950f5ea38b72
Create Date: 2025-04-20 09:30:09.544413

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '7ba304c8cf80'
down_revision: str | None = '950f5ea38b72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='fileprocessingstatus',
        new_values=[
            'pending',
            'queuing',
            'processing',
            'success',
            'failed',
            'cancelled',
            'unknown',
        ],
        affected_columns=[
            TableReference(table_schema='public', table_name='files', column_name='status')
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='fileprocessingstatus',
        new_values=['pending', 'processing', 'success', 'failed', 'cancelled', 'unknown'],
        affected_columns=[
            TableReference(table_schema='public', table_name='files', column_name='status')
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
