"""Add cascade delete to file table

Revision ID: 950f5ea38b72
Revises: 6592ad9f4e2c
Create Date: 2025-04-16 21:41:31.122178

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '950f5ea38b72'
down_revision: str | None = '6592ad9f4e2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_descriptions_file_id_fkey', 'file_descriptions', type_='foreignkey')
    op.create_foreign_key(
        None, 'file_descriptions', 'files', ['file_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_descriptions', type_='foreignkey')
    op.create_foreign_key(
        'file_descriptions_file_id_fkey', 'file_descriptions', 'files', ['file_id'], ['id']
    )
    # ### end Alembic commands ###
