"""Add file size and file type columns

Revision ID: 98f301e685ce
Revises: 54b63c19812d
Create Date: 2025-04-13 22:42:28.591296

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98f301e685ce'
down_revision: str | None = '54b63c19812d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'type')
    op.drop_column('files', 'size')
    # ### end Alembic commands ###
