"""Add some file columns

Revision ID: 9aab4d1bfaaf
Revises: 98f301e685ce
Create Date: 2025-04-15 09:44:10.358110

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9aab4d1bfaaf'
down_revision: str | None = '98f301e685ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('active_file_description_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('object_path', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'object_path')
    op.drop_column('files', 'active_file_description_id')
    # ### end Alembic commands ###
