"""Remove media stuff

Revision ID: 9c534056c364
Revises: c6948979f1e1
Create Date: 2025-04-22 16:18:09.819256

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c534056c364'
down_revision: str | None = 'c6948979f1e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_histories')
    op.drop_table('openverse_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'openverse_tokens',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'expires_in', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name='openverse_tokens_pkey'),
    )
    op.create_table(
        'media_histories',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='media_histories_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='media_histories_pkey'),
    )
    # ### end Alembic commands ###
