"""Add email verification columns

Revision ID: a12f06911705
Revises: 287d21c2e713
Create Date: 2025-03-12 14:36:37.028102

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a12f06911705'
down_revision: str | None = '287d21c2e713'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('verified', 'verifying', 'none', name='emailverificationstatus').create(op.get_bind())
    op.add_column(
        'users',
        sa.Column(
            'email_verification_status',
            postgresql.ENUM(
                'verified', 'verifying', 'none', name='emailverificationstatus', create_type=False
            ),
            nullable=False,
            server_default='none',
        ),
    )
    op.add_column(
        'users',
        sa.Column('email_verification_token', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verification_status')
    sa.Enum('verified', 'verifying', 'none', name='emailverificationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
