"""Remove file_descriptions table

Revision ID: c6948979f1e1
Revises: 7ba304c8cf80
Create Date: 2025-04-21 15:43:57.761549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6948979f1e1'
down_revision: str | None = '7ba304c8cf80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_descriptions')
    op.add_column('files', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('files', 'active_file_description_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'files',
        sa.Column('active_file_description_id', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column('files', 'description')
    op.create_table(
        'file_descriptions',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['file_id'], ['files.id'], name='file_descriptions_file_id_fkey', ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name='file_descriptions_pkey'),
    )
    # ### end Alembic commands ###
