"""Create auth sessions table

Revision ID: f649503e33b4
Revises: 4fb342b6ce04
Create Date: 2025-03-31 22:02:58.168993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f649503e33b4'
down_revision: str | None = '4fb342b6ce04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth_sessions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('expires_date', sa.DateTime(), nullable=False),
        sa.Column('token_version', sa.Uuid(), nullable=False),
        sa.Column('is_ended', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
