services:
  db:
    image: postgres:16.8
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: cmp9785
      POSTGRES_PASSWORD: abcd1234
    ports:
      - 5432:5432
  # api:
  #   build: .
  #   environment:
  #     AZURE_POSTGRESQL_HOST: db
  #     AZURE_POSTGRESQL_PORT: 5432
  #     AZURE_POSTGRESQL_DATABASE: postgres
  #     AZURE_POSTGRESQL_USERNAME: cmp9785
  #     AZURE_POSTGRESQL_PASSWORD: abcd1234
  #   ports:
  #     - "3001:80"
