name: Provision Resources
on:
  push:
    branches:
      - main
    paths:
      - infra/argocd/kustomization.yaml
      - infra/argocd/project.yaml
      - infra/argocd/apps/**
jobs:
  deploy:
    name: Deploy Kubernetes Manifests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/argocd/
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
      - name: Create kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV
      - name: Diff Kubernetes manifests
        run: kubectl diff -k . || true
      - name: Apply Kubernetes manifests
        run: kubectl apply -k .
      - name: Clean up kubeconfig
        if: always()
        run: rm -f kubeconfig.yaml
