name: Provision Resources
on:
  push:
    branches:
      - main
    paths:
      - infra/terraform/**
jobs:
  provision:
    name: Provision Resources
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
      TF_VAR_postgres_password: "${{ secrets.POSTGRES_PASSWORD }}"
      TF_VAR_auth_token_secret: "${{ secrets.AUTH_TOKEN_SECRET }}"
      TF_VAR_sendgrid_api_key: "${{ secrets.SENDGRID_API_KEY }}"
      TF_VAR_gemini_api_key: "${{ secrets.GEMINI_API_KEY }}"
    defaults:
      run:
        working-directory: infra/terraform/
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform plan
        run: terraform plan -out=tfplan -input=false
      - name: Terraform apply
        run: terraform apply -input=false tfplan
